config/routes.rb
Rails.application.routes.draw do

  root to: 'sessions#new'

  get '/signup', to: 'users#new'
  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  delete '/signout', to: 'sessions#destroy'

  resources :invitations, only: %i[new create]
  resources :users, only: %i[new create show]
  resources :events, only: %i[index new create show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :attendee, class_name: 'User'
  belongs_to :attended_event, class_name: 'Event'
end

app/models/event.rb
class Event < ApplicationRecord
  validates :title, presence: true, length: { maximum: 100 }
  validates :description, presence: true

  belongs_to :creator, class_name: 'User'
  has_many :attendances, foreign_key: 'attended_event_id'
  has_many :attendees, through: :attendances
  scope :past, -> { where('date < ?', Date.today) }
  scope :upcoming, -> { where('date >= ?', Date.today) }
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_FORMAT = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true, length: { maximum: 100 },
                    uniqueness: { case_sensitive: false },
                    format: { with: VALID_EMAIL_FORMAT }

  has_many :events, foreign_key: 'creator_id', class_name: 'Event'
  has_many :attendances, foreign_key: 'attendee_id'
  has_many :attended_events, through: :attendances
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :signed_in_user

  def index
    @past_events = Event.past.all
    @upcoming_events = Event.upcoming.all
  end

  def new
    @event = @user.events.build
  end

  def create
    @event = @user.events.build(user_params)
    if @event.save
      flash.now[:success] = 'Event created successfully'
      render 'show'
    else
      flash.now[:danger] = 'Invalid Event entry'
      render 'new'
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  private

  def user_params
    params.require(:event).permit(:title, :description, :date)
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_action :signed_in_user

  def new
    @invite = Attendance.new
    @event = Event.find_by(id: params[:event_id])
    @users = User.all.where.not(id: @user.id)
  end

  def create
    @invite = Attendance.new(
      attendee_id: params[:attendee_id],
      attended_event_id: params[:event_id]
    )
    if @invite.save
      flash[:success] = 'Invitation sent successfully'
      redirect_to user_path(@user)
    else
      redirect_to new_invitation_path(@event)
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(id: params[:session][:username]) || User.find_by(name: params[:session][:username])
    if user
      log_in user
      flash[:success] = 'Logged in successfully'
      redirect_to controller: 'users', action: 'show', id: user.id
    else
      flash.now[:danger] = 'Invalid ID or Name'
      render 'new'
    end
  end

  def destroy
    log_out
    flash[:success] = 'Logged out successfully'
    redirect_to root_url
  end

  private

  def user_params
    params.require(:user).permit(:username)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'Registered Successfully!!!'
      redirect_to root_url
    else
      flash[:danger] = 'Invalid entries found'
      render 'new'
    end
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def show
    if current_user.nil?
      flash[:danger] = 'You need to Signin'
      redirect_to root_url
    else
      @events = User.find(@current_user.id).events
      @upcoming_events = @current_user.attended_events.upcoming
      @past_events = @current_user.attended_events.past
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !@current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def signed_in_user
    @user = current_user
    return unless @user.nil?

    flash[:danger] = 'You need to signin'
    redirect_to root_url
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<h1>List of upcoming events</h1>

<%= render partial:'shared/event_list', locals:{events:@upcoming_events}%>

<h1>List of past events</h1>

<%= render partial:'shared/event_list', locals:{events:@past_events}%>

app/views/events/new.html.erb
<h1>Creat New event</h1>

<%= form_for(@event) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :description %>
  <%= f.text_area :description  %>
  <%= f.date_select :date  %>
  <%= f.submit "Create Event" %>
<% end %>

app/views/events/show.html.erb
<h1>Events show</h1>

<%= @event.title %>

<p>Organised by:<b> <%= @event.creator.name %> </b></p>

<% if !@event.attendances.collect.any? %>

  <h4>There are no attendees yet, How about inviting others here in the club?</h4>
  
  <%= button_to "Send Invitations", new_invitation_path, method: 'get', params: {event_id:@event.id} %>
<% else %>
<h2>List of Attendees for this event:</h2>

  <ul>
  <% @event.attendances.collect do |a| %>
    <li><%= a.attendee.name %></li>
  <% end %>
<% end %>
</ul>

app/views/invitations/new.html.erb
<h1>Send Invitations</h1>

<% @users.each do |user| %>
<ul>
  <li><%= user.name %><%= button_to 'Invite', invitations_path, method: 'post', params:{attendee_id:user.id, event_id:@event.id} %></li>
</ul>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |type, msg|  %>
  <div class="alert alert-<%= type %>"><%= msg %></div> 
<% end %>

app/views/layouts/_header.html.erb
<header>
  <% if logged_in? %>
    <ul>
      <li>Welcome <%= @current_user.name%>, </li>
      
      <li><%= link_to 'All Events', events_path %></li>
      <li><%= link_to 'Your Profile', user_path(@current_user) %></li>

      <li><%= link_to 'Signout', signout_path, method: 'delete' %></li>
    </ul>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/header'  %>
    <main>
    <%= render 'layouts/flash'  %>
    
    <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_event_list.html.erb
  <ul>
    <% events.each do |a|  %>
      <li><%= link_to a.title, event_path(a.id), method:'get' %></li>
    <% end %>
  </ul>

app/views/users/new.html.erb
<div class="register-form">

<h1>Registration form</h1>

<%= form_for(@user) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.submit "Register" %>
<% end %>

</div>

app/views/users/show.html.erb
<div class="event-show">

<% if !@events.empty? %>
  <h2>List of your posts</h2>
  <ul> 
    <% @events.each do |event| %>
      <li><%= event.title %> <%= button_to "Send Invitations", new_invitation_path, method: 'get', params: {event_id:event.id} %></li>
    <% end %>
  </ul>
  <%= link_to "Create a New event", new_event_path %>
<% else %>

  <h3>Heyyy, Why don't you create a new event??? </h3>
  <%= link_to "Create a New event", new_event_path %>
<% end %>

<% if @upcoming_events.empty? && @past_events.empty? %>
  <h3>Sorry, you dont have any Invitations to attend </h3>
<% else %>

  <h2>Events you planned to attend:</h2>
 
  <h3>Upcoming events</h3>
  
  <%= render 'shared/event_list', events:@upcoming_events%>

  <h3>Past events</h3>
  
  <%= render 'shared/event_list', events:@past_events%>
  
<% end %>
</div>